package com.example.api.dto

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.Size

/**
 * Carries the data required to update an existing automation rule.
 */
@Schema(description = "Payload used to update a configurable suggested-task automation rule.")
data class UpdateAutomationRuleRequest(
    @field:Schema(description = "Rule name shown in the UI.", example = "Post-watering moisture check")
    @field:NotBlank
    @field:Size(max = 120)
    val name: String,
    @field:Schema(description = "Whether the rule is enabled.", example = "true")
    val enabled: Boolean = true,
    @field:Schema(description = "Rule scope.", example = "ECOSYSTEM_TYPE", allowableValues = ["ALL_ECOSYSTEMS", "ECOSYSTEM_TYPE"])
    @field:NotBlank
    @field:Size(max = 40)
    val scopeType: String,
    @field:Schema(description = "Optional ecosystem type when the scope targets a specific type.", example = "FLORARIUM")
    @field:Size(max = 50)
    val ecosystemType: String? = null,
    @field:Schema(description = "Rule trigger type.", example = "AFTER_EVENT", allowableValues = ["AFTER_EVENT", "AFTER_INACTIVITY"])
    @field:NotBlank
    @field:Size(max = 40)
    val triggerType: String,
    @field:Schema(description = "Optional activity event type tied to the rule.", example = "WATERING")
    @field:Size(max = 50)
    val eventType: String? = null,
    @field:Schema(description = "Number of inactivity days before the rule triggers.", example = "7")
    @field:Min(1)
    @field:Max(365)
    val inactivityDays: Int? = null,
    @field:Schema(description = "Number of days to wait after the triggering event.", example = "2")
    @field:Min(0)
    @field:Max(365)
    val delayDays: Int? = null,
    @field:Schema(description = "Suggested task title generated by the rule.", example = "Check soil moisture")
    @field:NotBlank
    @field:Size(max = 160)
    val taskTitle: String,
    @field:Schema(description = "Generated task type.", example = "INSPECTION", allowableValues = ["WATERING", "FEEDING", "CLEANING", "INSPECTION"])
    @field:NotBlank
    @field:Size(max = 50)
    val taskType: String,
    @field:Schema(description = "Prevents creating a duplicate open task with the same signature.", example = "true")
    val preventDuplicates: Boolean = true
)
