version: '3'

services:
  db:
    image: postgres:15-alpine
    container_name: ecotracker-postgres
    restart: always
    environment:
      POSTGRES_USER: eco_user
      POSTGRES_PASSWORD: eco_password
      POSTGRES_DB: ecotracker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecotracker-network

volumes:
  postgres_data:

networks:
  ecotracker-network:
    name: ecotracker-network
