pipeline {
    agent any

    parameters {
        choice(
                name: 'ACTION',
                choices: ['up', 'down', 'stop', 'logs', 'ps'],
                description: '''Select what sql-build should do.
up    - start the PostgreSQL container and keep it running
down  - stop and remove the PostgreSQL container
stop  - stop the PostgreSQL container without removing it
logs  - show the latest database container logs
ps    - show current database container status'''
        )
    }

    stages {
        stage('SQL Control') {
            steps {
                dir('sql') {
                    script {
                        if (params.ACTION == 'up') {
                            sh 'docker compose up -d'
                        }

                        if (params.ACTION == 'stop') {
                            sh 'docker compose stop'
                        }

                        if (params.ACTION == 'down') {
                            sh 'docker compose down'
                        }

                        if (params.ACTION == 'logs') {
                            sh 'docker compose logs --no-color'
                        }

                        if (params.ACTION == 'ps') {
                            sh 'docker compose ps'
                        }
                    }
                }
            }
        }
    }
}
